title: Portfolio of Work
author: E. Ball
email: aeliza73@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio of work by Elizabeth Ball, Google Certified Data Engineer, 
  Technology professional, skilled in Linux/UNIX systems admin, 
  networking, Python, SQL, Agile methodology, JIRA, troubleshooting.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  aeliza73 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
